# Generated by Django 5.2.7 on 2025-10-16 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=100)),
                ('seriesName', models.CharField(max_length=100)),
                ('characterName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('releaseYear', models.IntegerField()),
                ('category', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('super-rare', 'Super Rare'), ('ultra-rare', 'Ultra Rare'), ('die-cast-rare', 'Die-Cast Rare'), ('parallels', 'Parallels'), ('refractor', 'Refractor'), ('autograph', 'Autograph'), ('dual-autograph', 'Dual Autograph'), ('signature', 'Signature')], max_length=20)),
                ('cardImage', models.ImageField(blank=True, upload_to='card_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
