# Generated by Django 5.2.7 on 2025-10-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cardImage',
        ),
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
    ]
