# Generated by Django 5.2.7 on 2025-10-16 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_card_cardimage_remove_card_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Super-Rare', 'Super Rare'), ('Ultra-Rare', 'Ultra Rare'), ('Die-Cast-Rare', 'Die-Cast Rare'), ('Parallels', 'Parallels'), ('Refractor', 'Refractor'), ('Autograph', 'Autograph'), ('Dual-Autograph', 'Dual Autograph'), ('Signature', 'Signature')], max_length=20),
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='card_images/')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.card')),
            ],
        ),
    ]
